title = "francium"
author = "francium"

baseURL = "/"
builddrafts = false
canonifyurls = true
languageCode = "en-us"
publishdir = "public"

theme = "hugo-theme-minos"
paginate = 50

[params]
noPostNavigation = true
customCss = ["css/main.css"]

[[menu.main]]
name                   = "Projects"
weight                 = 0
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "About"
weight                 = 0
identifier             = "about"
url                    = "/about/"
