title = "francium"
author = "francium"

baseURL = "/"
builddrafts = false
canonifyurls = true
languageCode = "en-us"
publishdir = "public"

theme = "hugo-theme-minos"
paginate = 50

[markup]
    [markup.highlight]
        guessSyntax = false
        style = "borland"
    [markup.goldmark.renderer]
        unsafe = true

[params]
    noPostNavigation = true
    customCss = ["css/main.css"]

[[menu.main]]
    name                   = "About"
    weight                 = 0
    identifier             = "about"
    url                    = "/about/"
